-- Insert all customer data provided by the user
INSERT INTO customers (name, accounts_receivable, status, created_at, updated_at) VALUES
('Agriculture, Rural Development Land & Environmental Affairs', 0.00, 'Paid', now(), now()),
('ALFA MUHY AUTO SPRAY PAINTING AND PANELBEATING', 0.00, 'Paid', now(), now()),
('Alinda Jacob Jr', 0.00, 'Paid', now(), now()),
('AZALE COMMUNICATIONS (PTY) LTD', 0.00, 'Paid', now(), now()),
('BATHO BAKOPANO DISABLED COMPOSED WAIST', 0.00, 'Paid', now(), now()),
('CHIEF EXECUTIVE OFFICER  SOUTH AFRICAN NATIONAL ROADS AGENCY SOC LIMITED', 0.00, 'Paid', now(), now()),
('Chulumanco Lilitha', -720.37, 'Overpaid', now(), now()),
('Department of Public Works,Road And Transport', 0.00, 'Paid', now(), now()),
('ENTHA MEDIA', 0.00, 'Paid', now(), now()),
('ESKOM ROTEK INDUSTRIES 4230', 0.00, 'Paid', now(), now()),
('FIKILE KUYENZEKA KUNGUMUSA', 0.00, 'Paid', now(), now()),
('FREESTYLE  KITCHEN AND CATERING', 0.00, 'Paid', now(), now()),
('Gauteng Department of e-Government', 0.00, 'Paid', now(), now()),
('George  munyonga', 0.00, 'Paid', now(), now()),
('Given', 0.00, 'Paid', now(), now()),
('Global Business Solutions', 18212.05, 'Unpaid', now(), now()),
('Highveld Worship Center', 0.00, 'Paid', now(), now()),
('JAMA KAMNISI TRADING AND PROJECTS', 1575.48, 'Unpaid', now(), now()),
('JO CHILOANE', 23179.19, 'Unpaid', now(), now()),
('KHAYA LAMI TRAVEL AND TOURS', 0.00, 'Paid', now(), now()),
('kuthele civil engineering and construction pty ltd', 0.00, 'Paid', now(), now()),
('M C MOTAU TRADING', 0.00, 'Paid', now(), now()),
('MABS MEDIA AGENCY', 5875.20, 'Unpaid', now(), now()),
('Madidi Property Management', 0.00, 'Paid', now(), now()),
('MANYUNYU LOGISTICS', 0.00, 'Paid', now(), now()),
('MDALUKWANE PROJECTS ENTERPRISE', -184.50, 'Overpaid', now(), now()),
('MOHAUMOLUTSI CIVIL WORKS', 0.00, 'Paid', now(), now()),
('Mr MTHOBISI DERRICK XABA', 0.00, 'Paid', now(), now()),
('Msukaligwa Local Municipality', 0.00, 'Paid', now(), now()),
('Musawenkosi Msibi', 0.00, 'Paid', now(), now()),
('NATHAN N NYANGUWO MEDICAL ORTHOTIST AND PROSTHETIST', 0.00, 'Paid', now(), now()),
('NKUDU TRADING', 0.00, 'Paid', now(), now()),
('NKUYAHAE HOLDINGS (PTY)LTD', 793.50, 'Unpaid', now(), now()),
('NSIBANDE MHURI TRADING AND PROJEC', -52.50, 'Overpaid', now(), now()),
('NTANDOSE TRADING AND PROJECTS', 0.00, 'Paid', now(), now()),
('OFENTSE SAMUEL MALAPANE', 0.00, 'Paid', now(), now()),
('OLEBILE BUSINESS ENTERPRISES (PTY) LTD', 0.00, 'Paid', now(), now()),
('ORIS POULTRY AND GENERAL TRADING', 0.00, 'Paid', now(), now()),
('PRETTY HOPE SMITH', 0.00, 'Paid', now(), now()),
('PROJECTS MANAGEMENT UNIT (PTY) LTD', 0.00, 'Paid', now(), now()),
('REDEEM GROUP', 0.00, 'Paid', now(), now()),
('Refithile Agency', -0.70, 'Overpaid', now(), now()),
('SANDICO ENTERPRISE', 0.00, 'Paid', now(), now()),
('SBONGIMPILENDE', 0.00, 'Paid', now(), now()),
('Sembo Collective', 0.00, 'Paid', now(), now()),
('SHAKWANENG BUSINESS ENTERPRISE', 0.00, 'Paid', now(), now()),
('Sibongile Molefi', 0.00, 'Paid', now(), now()),
('SILVER STEIN', 0.00, 'Paid', now(), now()),
('SIPHALI', -311.70, 'Overpaid', now(), now()),
('Soul keepers', 0.00, 'Paid', now(), now()),
('SP NGOBESE', 0.00, 'Paid', now(), now()),
('SSL PROJECTS AND SUPPLY', 814.20, 'Unpaid', now(), now()),
('STARLITE EDUCATORS', 0.00, 'Paid', now(), now()),
('Sthuthamagade Trading and Projects Cc', 0.00, 'Paid', now(), now()),
('Surprise Tuckshop & General', 128.14, 'Unpaid', now(), now()),
('Suzan Ramapulane', 1621.86, 'Unpaid', now(), now()),
('TECHLOGIX', 3266.00, 'Unpaid', now(), now()),
('THE LINK GROUP', 0.00, 'Paid', now(), now()),
('THE NEW ST SAMPSON APOSTOLIC CHURCH', 661.25, 'Unpaid', now(), now()),
('THOKOZA NHLANHLA INVESTMENTS', 2921.00, 'Unpaid', now(), now()),
('THOKOZA SIYAVUMA CONSTRUCTION AND PROJECTS', 10.00, 'Unpaid', now(), now()),
('TSANTSABANE ENGINEERING SOLUTION PTY LTD', 0.00, 'Paid', now(), now()),
('VILLAGE CINEMA LINE', 0.00, 'Paid', now(), now()),
('Vusisizwe Self Help And Projects', 0.00, 'Paid', now(), now()),
('WANDILE KITCHEN', 0.00, 'Paid', now(), now()),
('WILINGA TRADING (PTY) LTD', 0.00, 'Paid', now(), now()),
('YOWGATY', 440.80, 'Unpaid', now(), now()),
('DESIREE NOLWAZI LUTHULI', 0.00, 'Paid', now(), now()),
('FEZEKA CIVIL ENGINEERING AND CONSTRUCTION', 0.00, 'Paid', now(), now()),
('Joseph Innocent Langa', 0.00, 'Paid', now(), now())
ON CONFLICT (name) DO UPDATE SET
  accounts_receivable = EXCLUDED.accounts_receivable,
  status = EXCLUDED.status,
  updated_at = now();