import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Shield, Smartphone, Key, AlertTriangle, CheckCircle, Lock, QrCode } from 'lucide-react';

const SecurityMFA = () => {
  return (
    <div className="min-h-screen bg-background p-6">
      <div className="container mx-auto max-w-4xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">Account Security & MFA</h1>
          <p className="text-muted-foreground">
            Learn how to enhance your ClerkiQ account security using Multi-Factor Authentication (MFA).
          </p>
        </div>

        {/* Security Overview */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5" />
              Securing Your ClerkiQ Account with Multi-Factor Authentication (MFA)
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              At ClerkiQ, the security of your accounting data is our top priority. Adding Multi-Factor Authentication (MFA) 
              to your account provides a critical extra layer of security to protect sensitive financial information from unauthorized access.
            </p>
            <div className="p-4 bg-blue-50 rounded-lg">
              <div className="flex items-start gap-3">
                <Shield className="h-5 w-5 text-blue-500 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-medium text-blue-900">Enhanced Protection</p>
                  <p className="text-sm text-blue-700">
                    MFA significantly reduces the risk of unauthorized access, even if your password is compromised.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* What is MFA */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Key className="h-5 w-5" />
              What is Multi-Factor Authentication (MFA)?
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              Multi-Factor Authentication (MFA), sometimes called Two-Factor Authentication (2FA), adds a step to your 
              login process to verify your identity. Instead of just entering a password (something you know), MFA 
              requires you to provide an additional piece of evidence (something you have), typically a time-sensitive 
              code generated by an authenticator app on your smartphone.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <Lock className="h-6 w-6 text-primary" />
                    <h3 className="font-semibold">Something You Know</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Your password or PIN that only you should know.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <Smartphone className="h-6 w-6 text-primary" />
                    <h3 className="font-semibold">Something You Have</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Your smartphone with an authenticator app that generates time-sensitive codes.
                  </p>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>

        {/* Why Enable MFA */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Why Enable MFA?</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <Shield className="h-6 w-6 text-green-500" />
                    <h3 className="font-semibold">Enhanced Security</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Significantly reduces the risk of unauthorized account access, even if your password is compromised.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <Lock className="h-6 w-6 text-blue-500" />
                    <h3 className="font-semibold">Data Protection</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Protects sensitive client and firm financial data stored within ClerkiQ.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <CheckCircle className="h-6 w-6 text-purple-500" />
                    <h3 className="font-semibold">Compliance</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Helps meet security best practices and potential compliance requirements within the accounting industry.
                  </p>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>

        {/* Setting Up MFA */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <QrCode className="h-5 w-5" />
              Setting Up MFA in ClerkiQ
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="p-4 bg-orange-50 rounded-lg">
              <div className="flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-orange-500 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-medium text-orange-900">Before you begin:</p>
                  <p className="text-sm text-orange-700">
                    Ensure you have an authenticator app installed on your smartphone (e.g., Google Authenticator, Microsoft Authenticator, Authy).
                  </p>
                </div>
              </div>
            </div>

            <div>
              <h3 className="font-semibold mb-4">Follow these steps to enable MFA for your ClerkiQ account:</h3>
              <div className="space-y-4">
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">1</span>
                  <div>
                    <p className="font-medium">Log in to your ClerkiQ account.</p>
                    <p className="text-sm text-muted-foreground">Use your current username and password to access your account.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">2</span>
                  <div>
                    <p className="font-medium">Navigate to your Account Settings.</p>
                    <p className="text-sm text-muted-foreground">This is usually accessible from your user profile menu in the top-right corner.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">3</span>
                  <div>
                    <p className="font-medium">Find the Security section within your settings.</p>
                    <p className="text-sm text-muted-foreground">Look for the security or authentication section in your account settings.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">4</span>
                  <div>
                    <p className="font-medium">Locate the Multi-Factor Authentication (MFA) area and click the "Set up MFA" button.</p>
                    <p className="text-sm text-muted-foreground">A dialog box will appear to guide you through the setup process.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">5</span>
                  <div>
                    <p className="font-medium">Name Your Factor.</p>
                    <p className="text-sm text-muted-foreground">In the dialog, enter a descriptive name for your authenticator device (e.g., "My Work Phone", "Personal Authenticator"). This helps you identify it later if you add multiple factors. Click "Continue".</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">6</span>
                  <div>
                    <p className="font-medium">Scan the QR Code.</p>
                    <p className="text-sm text-muted-foreground">The application will now display a QR code. Open your authenticator app on your smartphone and use it to scan the QR code. Your app should automatically add your ClerkiQ account.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">7</span>
                  <div>
                    <p className="font-medium">Enter Verification Code.</p>
                    <p className="text-sm text-muted-foreground">Your authenticator app will display a 6-digit time-sensitive code. Enter this code into the input field provided in the ClerkiQ dialog.</p>
                  </div>
                </div>
                
                <div className="flex items-start gap-4">
                  <span className="bg-primary text-primary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">8</span>
                  <div>
                    <p className="font-medium">Enable MFA.</p>
                    <p className="text-sm text-muted-foreground">Click the "Enable MFA" button. If the code is correct, the MFA factor will be successfully added and verified for your account.</p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Using MFA */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Using MFA</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">After setting up MFA, your login process will slightly change:</p>
            <div className="space-y-4">
              <div className="flex items-start gap-4">
                <span className="bg-secondary text-secondary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">1</span>
                <div>
                  <p className="font-medium">Enter your email and password as usual.</p>
                  <p className="text-sm text-muted-foreground">This is the same first step as before.</p>
                </div>
              </div>
              
              <div className="flex items-start gap-4">
                <span className="bg-secondary text-secondary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">2</span>
                <div>
                  <p className="font-medium">You will be prompted to enter the current 6-digit code from your authenticator app.</p>
                  <p className="text-sm text-muted-foreground">Check your authenticator app for the current code.</p>
                </div>
              </div>
              
              <div className="flex items-start gap-4">
                <span className="bg-secondary text-secondary-foreground rounded-full w-8 h-8 flex items-center justify-center text-sm font-semibold flex-shrink-0">3</span>
                <div>
                  <p className="font-medium">Enter the code to complete the login.</p>
                  <p className="text-sm text-muted-foreground">Once verified, you'll have full access to your account.</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Recovery Codes */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Key className="h-5 w-5" />
              Managing Recovery Codes
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">Recovery codes are essential backups in case you lose access to your authenticator device.</p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <Shield className="h-6 w-6 text-orange-500" />
                    <h3 className="font-semibold">Store Safely</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Keep them separate from your primary device and password manager if possible (e.g., a secure physical location).
                  </p>
                </CardContent>
              </Card>
              
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <AlertTriangle className="h-6 w-6 text-red-500" />
                    <h3 className="font-semibold">Use Once</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    Each code can typically only be used once. Keep track of which codes you've used.
                  </p>
                </CardContent>
              </Card>
              
              <Card>
                <CardContent className="p-4">
                  <div className="flex items-center gap-3 mb-3">
                    <CheckCircle className="h-6 w-6 text-green-500" />
                    <h3 className="font-semibold">Regenerate if Needed</h3>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    If you lose your codes or suspect they are compromised, check your Security settings for an option to generate a new set.
                  </p>
                </CardContent>
              </Card>
            </div>
            
            <div className="p-4 bg-red-50 rounded-lg">
              <div className="flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-red-500 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-medium text-red-900">Important:</p>
                  <p className="text-sm text-red-700">
                    Regenerating recovery codes usually requires disabling and re-enabling MFA. Ensure you save the new codes securely.
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* CTA */}
        <Card>
          <CardContent className="p-6 text-center">
            <h3 className="text-xl font-semibold mb-2">Secure Your Account Today</h3>
            <p className="text-muted-foreground mb-4">
              Enable MFA to add an extra layer of protection to your ClerkiQ account and safeguard your financial data.
            </p>
            <Button size="lg" asChild>
              <a href="/auth">Access Account Settings</a>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default SecurityMFA;